### ISSUE TITLE
Feature request: return string of IP address for connected endpoint

### ISSUE THREAD

**Issue by KennethThompson** [KazDragon/serverpp#29]
#include <boost/lexical_cast.hpp>
std::string s = boost::lexical_cast<std::string>(socket.remote_endpoint());

Is it possible to add a method to the tcp_socket class so that the IP address of the endpoint is returned as a string?  The code above should work.  I would like to log the IP address & port of each incoming connection.

 I'm not skilled enough to submit a suggested change via git pull.

Thank you!

**Comment by KazDragon** [comment]
Hi Caliel.  That code does indeed work but I'm busy with family at the moment and wont have time to shepherd this through until next week.  However, if you want, instead of doing it, I could walk you through how to do a pull request.  That might be useful for other projects.  I guess from your time of posting you're in a USA timezone?

**Comment by KazDragon** [comment]
Finally got some time to do this.  The offer of walking you through pull requests stands open :)
